# Generated by Django 5.1.6 on 2025-05-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_student', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alerts')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('confirmed', 'Confirmed'), ('ignored', 'Ignored'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('isNotified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'date',
            },
        ),
    ]
