# Generated by Django 5.1.4 on 2025-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='alerts/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
