# Generated by Django 5.1.6 on 2025-05-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Leavings',
                'db_table': 'detector_Leaving',
            },
        ),
    ]
