# Generated by Django 5.1.4 on 2025-03-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_dashboard_alter_alert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
