# Generated by Django 5.1.6 on 2025-05-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_leaving'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaving',
            name='leaving',
            field=models.IntegerField(default=0),
        ),
    ]
