# Generated by Django 5.1.4 on 2025-03-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_alter_dashboard_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='alerts')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
