# Generated by Django 5.1.4 on 2025-03-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_violation_delete_alert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
