# Generated by Django 5.1.4 on 2025-03-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_alter_dashboard_options_alter_dashboard_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'get_latest_by': 'date', 'ordering': ['-id']},
        ),
    ]
