# Generated by Django 5.1.6 on 2025-04-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_alter_dashboard_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_student', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'date',
            },
        ),
        migrations.AlterModelOptions(
            name='violation',
            options={'get_latest_by': 'date', 'ordering': ['-id']},
        ),
    ]
