# Generated by Django 5.1.6 on 2025-05-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_student_alter_violation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='state',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('ignored', 'Ignored'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
