# Generated by Django 5.1.6 on 2025-05-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0008_alter_violation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='isNotified',
            field=models.BooleanField(default=False),
        ),
    ]
