# Generated by Django 5.1.6 on 2025-05-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0009_violation_isnotified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dashboard',
        ),
    ]
