# Generated by Django 5.1.6 on 2025-05-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0010_delete_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='student_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='detector.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='violation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
