# Generated by Django 5.1.6 on 2025-05-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0011_violation_student_id_alter_violation_id'),
        ('main', '0002_alter_secretary_password_alter_secretary_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='secretary_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='main.secretary'),
            preserve_default=False,
        ),
    ]
